config/routes.rb
Clarkdavedotnet::Application.routes.draw do

  get 'login' => 'sessions#new', :as => 'log_in'
  get 'logout' => 'sessions#destroy', :as => 'log_out'

  get 'about' => 'about#index'
  get 'contact' => 'contact#index'

  resources :blog, :controller => 'posts', :as => 'posts'
  resources :work, :controller => 'works', :as => 'works'
  post 'work/:id/create_thumb', :to => 'works#create_thumb'

  resources :users
  resources :sessions

  root :to => 'posts#index'

  

end

app/models/work.rb
require 'rdiscount'

class Work < ActiveRecord::Base

	has_attached_file :image

	def get_image_size
		return {:x => 0, :y => 0} unless image.present?

		Paperclip::Geometry.from_file(image.to_file)
		#{:x => geom.width.to_i, :y => geom.height.to_i }
	end

	def banner_thumb_url

		return nil unless image.exists?

		path = image.path.sub /(\.[^\?]+)/, '_banner.jpg'

		return nil unless File.exists(path)

		image.url.sub /(\.[^\?]+)/, '_banner.jpg'
	end

	def mini_thumb_url
		
		return nil unless image.exists?

		path = image.path.sub /(\.[^\?]+)/, '_mini.jpg'

		return nil unless File.exists(path)

		image.url.sub /(\.[^\?]+)/, '_mini.jpg'
	end


	def html_description
		RDiscount.new(description).to_html
	end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	# GET /works
	# GET /works.json
	def index
		@works = Work.order('completed DESC')

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @works }
		end
	end

	# GET /works/1
	# GET /works/1.json
	def show
		@work = Work.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @work }
		end
	end

	# GET /works/new
	# GET /works/new.json
	def new
		@work = Work.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @work }
		end
	end

	# GET /works/1/edit
	def edit
		@work = Work.find(params[:id])
	end

	# POST /works
	# POST /works.json
	def create
		@work = Work.new(params[:work])

		respond_to do |format|
			if @work.save
				format.html { redirect_to @work, notice: 'Work was successfully created.' }
				format.json { render json: @work, status: :created, location: @work }
			else
				format.html { render action: "new" }
				format.json { render json: @work.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /works/1
	# PUT /works/1.json
	def update
		@work = Work.find(params[:id])

		respond_to do |format|
			if @work.update_attributes(params[:work])
				format.html { redirect_to @work, notice: 'Work was successfully updated.' }
				format.json { head :ok }
			else
				format.html { render action: "edit" }
				format.json { render json: @work.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /works/1
	# DELETE /works/1.json
	def destroy
		@work = Work.find(params[:id])
		@work.destroy

		respond_to do |format|
			format.html { redirect_to works_url }
			format.json { head :ok }
		end
	end

	# POST /works
	def create_thumb
		@work = Work.find(params[:id])

		render :status => 501 if @work.nil?

		#puts @work.image.to_file.path
		
		size = @work.get_image_size
		width = size.width
		height = size.height
		new_path = @work.image.to_file.path.sub /(\..+)$/, "_#{params['type']}.jpg"

		#puts params
		#puts new_path
		
		Devil.with_image(@work.image.to_file.path) do |img|

			if params['scale'].to_i < 100 then
				scale = params['scale'].to_f / 100
				width = (width * scale).to_i
				height = (height * scale).to_i
				img.resize(width, height, :filter => Devil::SCALE_BSPLINE)
			end
			
			# for some reason the 2nd param, yoff, appears to count from the bottom of the image rather
			# than (as you'd think) the top... weird
			img.crop params['pos_x'].to_i, height - params['pos_y'].to_i - params['height'].to_i, 
				params['width'].to_i, params['height'].to_i
			img.save(new_path)

		end

		render :nothing => true

	end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<div class='work-form'>
	<h3><%= title %></h3>

	<%= form_for(@work) do |f| %>
		<% if @work.errors.any? %>
			<div id='error_explanation'>
				<h2><%= pluralize(@work.errors.count, 'error') %> prohibited this work from being saved:</h2>

				<ul>
				<% @work.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
		<% end %>

		<div class='field'>
			<%= f.label :name %>
			<%= f.text_field :name, :class => 'name' %>
		</div>
		<div class='field'>
			<%= f.label :tagline %>
			<%= f.text_field :tagline, :class => 'name' %>
		</div>
		<div class='field'>
			<%= f.label :completed %>
			<%= f.text_field :completed, :class => 'completed' %>
		</div>
		<div class='field'>
			<%= f.label :description %>
			<%= f.text_area :description, :cols => 30, :class => 'description' %>
		</div>
		<div class='field'>
			<%= f.label :url, 'URL' %>
			<%= f.text_field :url, :class => 'url' %>
		</div>
		<div class='field'>
			<%= f.label :image, (@work.image.nil? ? 'Upload image' : 'Upload a new image') %>
			<%= f.file_field :image %>
		</div>
		<% if not @work.image.nil? then %>
			<div class='field' style='margin-top: 20px'>
				<%= f.label 'Create thumbnails' %>
				<a id='thumb-create' href='#' title='<%= @work.get_image_size %>'>Create</a>
				<img id='thumb-create-src' src='<%= @work.image.url %>' style='display: none' />
			</div>
		<% end %>
		<div class='actions'>
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/works/edit.html.erb
<% content_for :title, 'edit' %>
<section id='content' class='work'>
	<%= render 'form', :title => 'Edit a work entry' %>
</section>

app/views/works/index.html.erb
<% content_for :title, 'work' %>
<section id='content' class='work'>
	<div class='work-chrono'>
		<% @works.each do |work| %>
			<div class='work-box'>

			</div>
		<% end %>
	</div>
	<div class='work-listing'>

		<h3>My work</h3>

		<% @works.each do |work| %>
			<div class='work-item'>
				<a href='<%= url_for work %>'>
					<% if work.banner_thumb_url then %>
					<div class='picture' style='background: url(<%= work.banner_thumb_url %>)'></div>
					<% else %>
					<div class='picture-placeholder'></div>
					<% end %>
				</a>
				<h4><%= link_to work.name, work %></h4>
				<p><%= work.tagline %></p>
			</div>
		<% end %>
	</div>
</section>

app/views/works/new.html.erb
<% content_for :title, 'new' %>
<section id='content' class='work'>
	<%= render 'form', :title => 'Create a new work entry' %>
</section>

app/views/works/show.html.erb
<% content_for :title, @work.name %>
<section id='content' class='work'>
	<div class='work-detail-techs'>
		<% if logged_in? %>
			<a class='edit' href='<%= edit_work_path @work %>'></a>
		<% end %>
		<div class='dim'>
			<div class='tech'><span>php</span></div>
			<div class='tech'><span>mysql</span></div>
			<div class='tech'><abbr title='Zend PHP Framework'>zend</abbr></div>
			<div class='tech'><span>jquery</span></div>
		</div>
	</div>
	<div class='work-detail'>

		<h3><%= @work.name %></h3>
		<div class='detail-box'>
			<a href='#'><div class='picture' style='background-image: url(<%= @work.image.url %>)'></div></a>
			<div class='status'>
				<% unless @work.completed.nil? %>
				<p class='date'><strong>Completed:</strong> <%= @work.completed.strftime('%B %Y') %></p>
				<% end %>
				<% unless @work.url.nil? %>
				<p class='url'><strong>URL:</strong> <a href='<%= @work.url %>'><%= @work.url %></a></p>
				<% end %>
			</div>
			<div class='description'>
				<%=raw @work.html_description %>
			</div>
		</div>
		
	</div>
</section>